export const mapaCamposFormulario = [
  { anterior: 'firstName', actual: 'primerNombre', descripcion: 'Primer nombre del cliente' },
  { anterior: 'middleName', actual: 'segundoNombre', descripcion: 'Segundo nombre del cliente' },
  { anterior: 'paternalLastName', actual: 'primerApellido', descripcion: 'Primer apellido del cliente' },
  { anterior: 'maternalLastName', actual: 'segundoApellido', descripcion: 'Segundo apellido del cliente' },
  { anterior: 'fullName', actual: 'nombreCompleto', descripcion: 'Nombre completo generado antes del envio' },
  { anterior: 'birthdate', actual: 'fechaNacimiento', descripcion: 'Fecha de nacimiento del cliente' },
  { anterior: 'sex', actual: 'sexo', descripcion: 'Sexo del cliente' },
  { anterior: 'maritalStatus', actual: 'estadoCivil', descripcion: 'Estado civil' },
  { anterior: 'spouseFirstNames', actual: 'nombresConyuge', descripcion: 'Nombres del conyuge' },
  { anterior: 'spouseLastNames', actual: 'apellidosConyuge', descripcion: 'Apellidos del conyuge' },
  { anterior: 'spouseName', actual: 'nombreConyuge', descripcion: 'Nombre completo del conyuge' },
  { anterior: 'spouseBirthdate', actual: 'fechaNacimientoConyuge', descripcion: 'Fecha de nacimiento del conyuge' },
  { anterior: 'spouseNationality', actual: 'nacionalidadConyuge', descripcion: 'Nacionalidad del conyuge' },
  { anterior: 'spouseBirthCountry', actual: 'paisNacimientoConyuge', descripcion: 'Pais de nacimiento del conyuge' },
  { anterior: 'spouseBirthCity', actual: 'ciudadNacimientoConyuge', descripcion: 'Ciudad de nacimiento del conyuge' },
  { anterior: 'spouseAddress', actual: 'direccionConyuge', descripcion: 'Direccion del conyuge' },
  { anterior: 'spouseAddressOther', actual: 'direccionConyugeOtro', descripcion: 'Direccion del conyuge especificada' },
  { anterior: 'nationality', actual: 'nacionalidad', descripcion: 'Nacionalidad principal' },
  { anterior: 'hasOtherNationality', actual: 'tieneOtraNacionalidad', descripcion: 'Indica si tiene otra nacionalidad' },
  { anterior: 'otherNationality', actual: 'otraNacionalidad', descripcion: 'Otra nacionalidad declarada' },
  { anterior: 'isPermanentResidentAbroad', actual: 'esResidentePermanenteExtranjero', descripcion: 'Residencia permanente fuera del pais de nacimiento' },
  { anterior: 'permanentResidentCountry', actual: 'paisResidenciaPermanente', descripcion: 'Pais de residencia permanente' },
  { anterior: 'homePhone', actual: 'telefonoDomicilio', descripcion: 'Telefono de domicilio' },
  { anterior: 'city', actual: 'ciudad', descripcion: 'Ciudad de domicilio' },
  { anterior: 'province', actual: 'provincia', descripcion: 'Provincia de domicilio' },
  { anterior: 'cellPhone', actual: 'celular', descripcion: 'Telefono celular' },
  { anterior: 'hasPreviousPhones', actual: 'tuvoTelefonosAnteriores', descripcion: 'Indica si tuvo otros telefonos en los ultimos 5 anos' },
  { anterior: 'previousPhones', actual: 'telefonosAnteriores', descripcion: 'Otros telefonos de los ultimos 5 anos' },
  { anterior: 'address', actual: 'direccion', descripcion: 'Direccion exacta de domicilio' },
  { anterior: 'postalCode', actual: 'codigoPostal', descripcion: 'Codigo postal de domicilio' },
  { anterior: 'email', actual: 'correo', descripcion: 'Correo electronico principal' },
  { anterior: 'hasPreviousEmails', actual: 'tuvoCorreosAnteriores', descripcion: 'Indica si tuvo correos anteriores' },
  { anterior: 'previousEmails', actual: 'correosAnteriores', descripcion: 'Correo anterior' },
  { anterior: 'passportCity', actual: 'ciudadPasaporte', descripcion: 'Ciudad donde tramito el pasaporte' },
  { anterior: 'passportLostOrStolen', actual: 'pasaportePerdidoORobado', descripcion: 'Pasaporte perdido o robado' },
  { anterior: 'lostPassportNumber', actual: 'numeroPasaportePerdidoORobado', descripcion: 'Numero de pasaporte o documento de viaje perdido o robado' },
  { anterior: 'lostPassportIssuingAuthority', actual: 'paisAutoridadPasaportePerdidoORobado', descripcion: 'Pais o autoridad que emitio el pasaporte o documento de viaje' },
  { anterior: 'lostPassportExplanation', actual: 'explicacionPasaportePerdidoORobado', descripcion: 'Explicacion del pasaporte o documento de viaje perdido o robado' },
  { anterior: 'usDriversLicense', actual: 'licenciaConducirEEUU', descripcion: 'Licencia de conducir de EE.UU.' },
  { anterior: 'hasUsTaxId', actual: 'tieneIdentificacionFiscalEEUU', descripcion: 'Tiene identificacion fiscal de EE.UU.' },
  { anterior: 'usTaxId', actual: 'identificacionFiscalEEUU', descripcion: 'Numero de identificacion fiscal de EE.UU.' },
  { anterior: 'currentOccupationCategory', actual: 'categoriaOcupacionActual', descripcion: 'Categoria de ocupacion actual' },
  { anterior: 'currentPosition', actual: 'cargoActual', descripcion: 'Cargo actual' },
  { anterior: 'currentEmployer', actual: 'empleadorActual', descripcion: 'Empleador actual' },
  { anterior: 'currentJobDescription', actual: 'descripcionTrabajoActual', descripcion: 'Descripcion del trabajo actual' },
  { anterior: 'currentSalary', actual: 'sueldoActual', descripcion: 'Sueldo mensual actual' },
  { anterior: 'currentJobAddress', actual: 'direccionTrabajoActual', descripcion: 'Direccion del trabajo actual' },
  { anterior: 'currentJobCity', actual: 'ciudadTrabajoActual', descripcion: 'Ciudad del trabajo actual' },
  { anterior: 'currentJobProvince', actual: 'provinciaTrabajoActual', descripcion: 'Provincia del trabajo actual' },
  { anterior: 'currentJobPostalCode', actual: 'codigoPostalTrabajoActual', descripcion: 'Codigo postal del trabajo actual' },
  { anterior: 'currentJobPhone', actual: 'telefonoTrabajoActual', descripcion: 'Telefono del trabajo actual' },
  { anterior: 'currentJobStartDate', actual: 'fechaInicioTrabajoActual', descripcion: 'Fecha de inicio del trabajo actual' },
  { anterior: 'hasPreviousJob', actual: 'tuvoTrabajoAnterior', descripcion: 'Indica si tuvo trabajo anterior' },
  { anterior: 'previousEmployer', actual: 'empleadorAnterior', descripcion: 'Empleador anterior' },
  { anterior: 'previousPosition', actual: 'cargoAnterior', descripcion: 'Cargo anterior' },
  { anterior: 'previousJobAddress', actual: 'direccionTrabajoAnterior', descripcion: 'Direccion del trabajo anterior' },
  { anterior: 'previousJobCity', actual: 'ciudadTrabajoAnterior', descripcion: 'Ciudad del trabajo anterior' },
  { anterior: 'previousJobProvince', actual: 'provinciaTrabajoAnterior', descripcion: 'Provincia del trabajo anterior' },
  { anterior: 'previousJobPostalCode', actual: 'codigoPostalTrabajoAnterior', descripcion: 'Codigo postal del trabajo anterior' },
  { anterior: 'previousJobPhone', actual: 'telefonoTrabajoAnterior', descripcion: 'Telefono del trabajo anterior' },
  { anterior: 'previousSupervisorName', actual: 'nombreSupervisorAnterior', descripcion: 'Nombre del supervisor anterior' },
  { anterior: 'previousSupervisorLastName', actual: 'apellidosSupervisorAnterior', descripcion: 'Apellidos del supervisor anterior' },
  { anterior: 'previousJobDescription', actual: 'descripcionTrabajoAnterior', descripcion: 'Descripcion del trabajo anterior' },
  { anterior: 'previousJobStartDate', actual: 'fechaInicioTrabajoAnterior', descripcion: 'Fecha de inicio del trabajo anterior' },
  { anterior: 'previousJobEndDate', actual: 'fechaFinTrabajoAnterior', descripcion: 'Fecha de fin del trabajo anterior' },
  { anterior: 'hasSecondaryOrHigherEducation', actual: 'asistioInstitucionEducativa', descripcion: 'Asistio a una institucion educativa secundaria o superior' },
  { anterior: 'bachelorInstitution', actual: 'institucionBachillerato', descripcion: 'Institucion de bachillerato' },
  { anterior: 'universityInstitution', actual: 'institucionUniversitaria', descripcion: 'Institucion universitaria' },
  { anterior: 'careerName', actual: 'nombreCarrera', descripcion: 'Carrera o programa' },
  { anterior: 'educationAddress', actual: 'direccionEducacion', descripcion: 'Direccion de la institucion educativa' },
  { anterior: 'educationCity', actual: 'ciudadEducacion', descripcion: 'Ciudad de la institucion educativa' },
  { anterior: 'educationProvince', actual: 'provinciaEducacion', descripcion: 'Provincia de la institucion educativa' },
  { anterior: 'educationPostalCode', actual: 'codigoPostalEducacion', descripcion: 'Codigo postal de la institucion educativa' },
  { anterior: 'educationStartDate', actual: 'fechaInicioEducacion', descripcion: 'Fecha de inicio de educacion' },
  { anterior: 'educationEndDate', actual: 'fechaFinEducacion', descripcion: 'Fecha de finalizacion de educacion' },
  { anterior: 'languages', actual: 'idiomas', descripcion: 'Idiomas que habla' },
  { anterior: 'fatherFirstNames', actual: 'nombresPadre', descripcion: 'Nombres del padre' },
  { anterior: 'fatherLastNames', actual: 'apellidosPadre', descripcion: 'Apellidos del padre' },
  { anterior: 'fatherName', actual: 'nombrePadre', descripcion: 'Nombre completo del padre generado antes del envio' },
  { anterior: 'fatherBirthdate', actual: 'fechaNacimientoPadre', descripcion: 'Fecha de nacimiento del padre' },
  { anterior: 'fatherInUSA', actual: 'padreEnEEUU', descripcion: 'Indica si el padre esta en EE.UU.' },
  { anterior: 'fatherUsStatus', actual: 'estatusPadreEEUU', descripcion: 'Estatus del padre en EE.UU.' },
  { anterior: 'motherFirstNames', actual: 'nombresMadre', descripcion: 'Nombres de la madre' },
  { anterior: 'motherLastNames', actual: 'apellidosMadre', descripcion: 'Apellidos de la madre' },
  { anterior: 'motherName', actual: 'nombreMadre', descripcion: 'Nombre completo de la madre generado antes del envio' },
  { anterior: 'motherBirthdate', actual: 'fechaNacimientoMadre', descripcion: 'Fecha de nacimiento de la madre' },
  { anterior: 'motherInUSA', actual: 'madreEnEEUU', descripcion: 'Indica si la madre esta en EE.UU.' },
  { anterior: 'motherUsStatus', actual: 'estatusMadreEEUU', descripcion: 'Estatus de la madre en EE.UU.' },
  { anterior: 'immediateRelativesInUSA', actual: 'familiaresInmediatosEnEEUU', descripcion: 'Familiares inmediatos en EE.UU.' },
  { anterior: 'immediateRelativesDetails', actual: 'familiaresInmediatosDetalle', descripcion: 'Detalle de familiares inmediatos en EE.UU.' },
  { anterior: 'otherRelativesInUSA', actual: 'otrosFamiliaresEnEEUU', descripcion: 'Otros familiares en EE.UU.' },
  { anterior: 'tripPurposeCategory', actual: 'categoriaMotivoViaje', descripcion: 'Categoria o razon de viaje' },
  { anterior: 'tripPurpose', actual: 'tipoVisa', descripcion: 'Motivo Especifico solicitado' },
  { anterior: 'tripPayer', actual: 'pagadorViaje', descripcion: 'Persona u organizacion que paga el viaje' },
  { anterior: 'travelingWithOthers', actual: 'viajaConOtros', descripcion: 'Indica si viaja con otras personas' },
  { anterior: 'travelCompanions', actual: 'acompanantesViaje', descripcion: 'Lista de acompanantes de viaje' },
  { anterior: 'hasVisitedUS', actual: 'haVisitadoEEUU', descripcion: 'Indica si ha visitado EE.UU.' },
  { anterior: 'previousUSVisits', actual: 'visitasAnterioresEEUU', descripcion: 'Historial de visitas anteriores a EE.UU.' },
  { anterior: 'hasBeenIssuedUSVisa', actual: 'haTenidoVisaEEUU', descripcion: 'Indica si tuvo visa de EE.UU.' },
  { anterior: 'visaDenied', actual: 'visaNegada', descripcion: 'Indica si le han negado una visa' },
  { anterior: 'hasImmigrationPetition', actual: 'tienePeticionInmigracion', descripcion: 'Peticion de inmigracion presentada a su nombre' },
  { anterior: 'contagiousDisease', actual: 'enfermedadContagiosa', descripcion: 'Enfermedad contagiosa' },
  { anterior: 'contagiousDiseaseDetails', actual: 'detalleEnfermedadContagiosa', descripcion: 'Detalle de enfermedad contagiosa' },
] as const
