// Archivo generado por scripts/generarCatalogos.mjs — no editar a mano.
// Fuente: docs/catalogo_estados_eeuu.md

import type { OpcionCatalogo } from './tipos'

export const estadosEEUU = [
  { valor: 'AL', texto: 'Alabama' },
  { valor: 'AK', texto: 'Alaska' },
  { valor: 'AS', texto: 'Samoa Americana' },
  { valor: 'AZ', texto: 'Arizona' },
  { valor: 'AR', texto: 'Arkansas' },
  { valor: 'CA', texto: 'California' },
  { valor: 'CO', texto: 'Colorado' },
  { valor: 'CT', texto: 'Connecticut' },
  { valor: 'DE', texto: 'Delaware' },
  { valor: 'DC', texto: 'Distrito de Columbia' },
  { valor: 'FL', texto: 'Florida' },
  { valor: 'GA', texto: 'Georgia' },
  { valor: 'GU', texto: 'Guam' },
  { valor: 'HI', texto: 'Hawái' },
  { valor: 'ID', texto: 'Idaho' },
  { valor: 'IL', texto: 'Illinois' },
  { valor: 'IN', texto: 'Indiana' },
  { valor: 'IA', texto: 'Iowa' },
  { valor: 'KS', texto: 'Kansas' },
  { valor: 'KY', texto: 'Kentucky' },
  { valor: 'LA', texto: 'Luisiana' },
  { valor: 'ME', texto: 'Maine' },
  { valor: 'MD', texto: 'Maryland' },
  { valor: 'MA', texto: 'Massachusetts' },
  { valor: 'MI', texto: 'Míchigan' },
  { valor: 'MN', texto: 'Minnesota' },
  { valor: 'MS', texto: 'Misisipi' },
  { valor: 'MO', texto: 'Misuri' },
  { valor: 'MT', texto: 'Montana' },
  { valor: 'NE', texto: 'Nebraska' },
  { valor: 'NV', texto: 'Nevada' },
  { valor: 'NH', texto: 'Nuevo Hampshire' },
  { valor: 'NJ', texto: 'Nueva Jersey' },
  { valor: 'NM', texto: 'Nuevo México' },
  { valor: 'NY', texto: 'Nueva York' },
  { valor: 'NC', texto: 'Carolina del Norte' },
  { valor: 'ND', texto: 'Dakota del Norte' },
  { valor: 'MP', texto: 'Islas Marianas del Norte' },
  { valor: 'OH', texto: 'Ohio' },
  { valor: 'OK', texto: 'Oklahoma' },
  { valor: 'OR', texto: 'Oregón' },
  { valor: 'PA', texto: 'Pensilvania' },
  { valor: 'PR', texto: 'Puerto Rico' },
  { valor: 'RI', texto: 'Rhode Island' },
  { valor: 'SC', texto: 'Carolina del Sur' },
  { valor: 'SD', texto: 'Dakota del Sur' },
  { valor: 'TN', texto: 'Tennessee' },
  { valor: 'TX', texto: 'Texas' },
  { valor: 'UT', texto: 'Utah' },
  { valor: 'VT', texto: 'Vermont' },
  { valor: 'VI', texto: 'Islas Vírgenes' },
  { valor: 'VA', texto: 'Virginia' },
  { valor: 'WA', texto: 'Washington' },
  { valor: 'WV', texto: 'Virginia Occidental' },
  { valor: 'WI', texto: 'Wisconsin' },
  { valor: 'WY', texto: 'Wyoming' },
] as const satisfies readonly OpcionCatalogo[]
