// Archivo generado por scripts/generarCatalogos.mjs — no editar a mano.

export type { OpcionCatalogo } from './tipos'
export { valoresDe } from './tipos'
export { estadoCivil } from './estadoCivil'
export { estadosEEUU } from './estadosEEUU'
export { estatusEEUU } from './estatusEEUU'
export { ocupacionActual } from './ocupacionActual'
export { paisesAutoridadPasaporte } from './paisesAutoridadPasaporte'
export { paisesLugarNacimiento } from './paisesLugarNacimiento'
export { paisesNacionalidad } from './paisesNacionalidad'
export { paisesNacionalidadConyuge } from './paisesNacionalidadConyuge'
export { paisesResidenciaPermanente } from './paisesResidenciaPermanente'
export { parentescoFamiliarEEUU } from './parentescoFamiliarEEUU'
export { propositoViaje } from './propositoViaje'
export { propositoViajeEspecifico } from './propositoViajeEspecifico'
export { quienPaga } from './quienPaga'
export { relacionAcompanante } from './relacionAcompanante'
export { relacionContactoEEUU } from './relacionContactoEEUU'
export { relacionPagador } from './relacionPagador'
export { sexo } from './sexo'
export { tipoDocumentoPasaporte } from './tipoDocumentoPasaporte'
export { unidadDuracion } from './unidadDuracion'
