// Archivo generado por scripts/generarCatalogos.mjs — no editar a mano.
// Fuente: docs/catalogo_paises_nacionalidad_conyuge.md

import type { OpcionCatalogo } from './tipos'

export const paisesNacionalidadConyuge = [
  { valor: 'AFGH', texto: 'Afganistán' },
  { valor: 'ALB', texto: 'Albania' },
  { valor: 'ALGR', texto: 'Argelia' },
  { valor: 'ANDO', texto: 'Andorra' },
  { valor: 'ANGL', texto: 'Angola' },
  { valor: 'ANGU', texto: 'Anguila' },
  { valor: 'ANTI', texto: 'Antigua y Barbuda' },
  { valor: 'ARG', texto: 'Argentina' },
  { valor: 'ARM', texto: 'Armenia' },
  { valor: 'ASTL', texto: 'Australia' },
  { valor: 'AUST', texto: 'Austria' },
  { valor: 'AZR', texto: 'Azerbaiyán' },
  { valor: 'BAMA', texto: 'Bahamas' },
  { valor: 'BAHR', texto: 'Baréin' },
  { valor: 'BANG', texto: 'Bangladés' },
  { valor: 'BRDO', texto: 'Barbados' },
  { valor: 'BYS', texto: 'Bielorrusia' },
  { valor: 'BELG', texto: 'Bélgica' },
  { valor: 'BLZ', texto: 'Belice' },
  { valor: 'BENN', texto: 'Benín' },
  { valor: 'BERM', texto: 'Bermudas' },
  { valor: 'BHU', texto: 'Bután' },
  { valor: 'BOL', texto: 'Bolivia' },
  { valor: 'BIH', texto: 'Bosnia y Herzegovina' },
  { valor: 'BOT', texto: 'Botsuana' },
  { valor: 'BRZL', texto: 'Brasil' },
  { valor: 'BRNI', texto: 'Brunéi' },
  { valor: 'BULG', texto: 'Bulgaria' },
  { valor: 'BURK', texto: 'Burkina Faso' },
  { valor: 'BURM', texto: 'Birmania (Myanmar)' },
  { valor: 'BRND', texto: 'Burundi' },
  { valor: 'CBDA', texto: 'Camboya' },
  { valor: 'CMRN', texto: 'Camerún' },
  { valor: 'CAN', texto: 'Canadá' },
  { valor: 'CAVI', texto: 'Cabo Verde' },
  { valor: 'CAYI', texto: 'Islas Caimán' },
  { valor: 'CAFR', texto: 'República Centroafricana' },
  { valor: 'CHAD', texto: 'Chad' },
  { valor: 'CHIL', texto: 'Chile' },
  { valor: 'CHIN', texto: 'China' },
  { valor: 'COL', texto: 'Colombia' },
  { valor: 'COMO', texto: 'Comoras' },
  { valor: 'COD', texto: 'Congo, República Democrática del' },
  { valor: 'CONB', texto: 'Congo, República del' },
  { valor: 'CSTR', texto: 'Costa Rica' },
  { valor: 'IVCO', texto: 'Costa de Marfil' },
  { valor: 'HRV', texto: 'Croacia' },
  { valor: 'CUBA', texto: 'Cuba' },
  { valor: 'CYPR', texto: 'Chipre' },
  { valor: 'CZEC', texto: 'República Checa' },
  { valor: 'DEN', texto: 'Dinamarca' },
  { valor: 'DJI', texto: 'Yibuti' },
  { valor: 'DOMN', texto: 'Dominica' },
  { valor: 'DOMR', texto: 'República Dominicana' },
  { valor: 'ECUA', texto: 'Ecuador' },
  { valor: 'EGYP', texto: 'Egipto' },
  { valor: 'ELSL', texto: 'El Salvador' },
  { valor: 'EGN', texto: 'Guinea Ecuatorial' },
  { valor: 'ERI', texto: 'Eritrea' },
  { valor: 'EST', texto: 'Estonia' },
  { valor: 'SZLD', texto: 'Esuatini' },
  { valor: 'ETH', texto: 'Etiopía' },
  { valor: 'FIJI', texto: 'Fiyi' },
  { valor: 'FIN', texto: 'Finlandia' },
  { valor: 'FRAN', texto: 'Francia' },
  { valor: 'GABN', texto: 'Gabón' },
  { valor: 'GAM', texto: 'Gambia' },
  { valor: 'GEO', texto: 'Georgia' },
  { valor: 'GER', texto: 'Alemania' },
  { valor: 'GHAN', texto: 'Ghana' },
  { valor: 'GIB', texto: 'Gibraltar' },
  { valor: 'GRC', texto: 'Grecia' },
  { valor: 'GREN', texto: 'Granada' },
  { valor: 'GUAT', texto: 'Guatemala' },
  { valor: 'GNEA', texto: 'Guinea' },
  { valor: 'GUIB', texto: 'Guinea-Bisáu' },
  { valor: 'GUY', texto: 'Guyana' },
  { valor: 'HAT', texto: 'Haití' },
  { valor: 'VAT', texto: 'Santa Sede (Ciudad del Vaticano)' },
  { valor: 'HOND', texto: 'Honduras' },
  { valor: 'HOKO', texto: 'Hong Kong BNO' },
  { valor: 'HNK', texto: 'Hong Kong RAE' },
  { valor: 'HUNG', texto: 'Hungría' },
  { valor: 'ICLD', texto: 'Islandia' },
  { valor: 'IND', texto: 'India' },
  { valor: 'IDSA', texto: 'Indonesia' },
  { valor: 'IRAN', texto: 'Irán' },
  { valor: 'IRAQ', texto: 'Irak' },
  { valor: 'IRE', texto: 'Irlanda' },
  { valor: 'ISRL', texto: 'Israel' },
  { valor: 'ITLY', texto: 'Italia' },
  { valor: 'JAM', texto: 'Jamaica' },
  { valor: 'JPN', texto: 'Japón' },
  { valor: 'JORD', texto: 'Jordania' },
  { valor: 'KAZ', texto: 'Kazajistán' },
  { valor: 'KENY', texto: 'Kenia' },
  { valor: 'KIRI', texto: 'Kiribati' },
  { valor: 'PRK', texto: 'Corea del Norte' },
  { valor: 'KOR', texto: 'Corea del Sur' },
  { valor: 'KSV', texto: 'Kosovo' },
  { valor: 'KUWT', texto: 'Kuwait' },
  { valor: 'KGZ', texto: 'Kirguistán' },
  { valor: 'LAOS', texto: 'Laos' },
  { valor: 'LATV', texto: 'Letonia' },
  { valor: 'LEBN', texto: 'Líbano' },
  { valor: 'LES', texto: 'Lesoto' },
  { valor: 'LIBR', texto: 'Liberia' },
  { valor: 'LBYA', texto: 'Libia' },
  { valor: 'LCHT', texto: 'Liechtenstein' },
  { valor: 'LITH', texto: 'Lituania' },
  { valor: 'LXM', texto: 'Luxemburgo' },
  { valor: 'MAC', texto: 'Macao' },
  { valor: 'MKD', texto: 'Macedonia del Norte' },
  { valor: 'MADG', texto: 'Madagascar' },
  { valor: 'MALW', texto: 'Malaui' },
  { valor: 'MLAS', texto: 'Malasia' },
  { valor: 'MLDV', texto: 'Maldivas' },
  { valor: 'MALI', texto: 'Malí' },
  { valor: 'MLTA', texto: 'Malta' },
  { valor: 'RMI', texto: 'Islas Marshall' },
  { valor: 'MAUR', texto: 'Mauritania' },
  { valor: 'MRTS', texto: 'Mauricio' },
  { valor: 'MEX', texto: 'México' },
  { valor: 'FSM', texto: 'Micronesia' },
  { valor: 'MLD', texto: 'Moldavia' },
  { valor: 'MON', texto: 'Mónaco' },
  { valor: 'MONG', texto: 'Mongolia' },
  { valor: 'MTG', texto: 'Montenegro' },
  { valor: 'MONT', texto: 'Montserrat' },
  { valor: 'MORO', texto: 'Marruecos' },
  { valor: 'MOZ', texto: 'Mozambique' },
  { valor: 'NAMB', texto: 'Namibia' },
  { valor: 'NAU', texto: 'Nauru' },
  { valor: 'NEP', texto: 'Nepal' },
  { valor: 'NETH', texto: 'Países Bajos' },
  { valor: 'NZLD', texto: 'Nueva Zelanda' },
  { valor: 'NIC', texto: 'Nicaragua' },
  { valor: 'NIR', texto: 'Níger' },
  { valor: 'NRA', texto: 'Nigeria' },
  { valor: 'NORW', texto: 'Noruega' },
  { valor: 'OMAN', texto: 'Omán' },
  { valor: 'PKST', texto: 'Pakistán' },
  { valor: 'PALA', texto: 'Palaos' },
  { valor: 'PAL', texto: 'Autoridad Palestina' },
  { valor: 'PAN', texto: 'Panamá' },
  { valor: 'PNG', texto: 'Papúa Nueva Guinea' },
  { valor: 'PARA', texto: 'Paraguay' },
  { valor: 'PERU', texto: 'Perú' },
  { valor: 'PHIL', texto: 'Filipinas' },
  { valor: 'PITC', texto: 'Islas Pitcairn' },
  { valor: 'POL', texto: 'Polonia' },
  { valor: 'PORT', texto: 'Portugal' },
  { valor: 'QTAR', texto: 'Catar' },
  { valor: 'ROM', texto: 'Rumania' },
  { valor: 'RUS', texto: 'Rusia' },
  { valor: 'RWND', texto: 'Ruanda' },
  { valor: 'WSAM', texto: 'Samoa' },
  { valor: 'SMAR', texto: 'San Marino' },
  { valor: 'STPR', texto: 'Santo Tomé y Príncipe' },
  { valor: 'SARB', texto: 'Arabia Saudita' },
  { valor: 'SENG', texto: 'Senegal' },
  { valor: 'SBA', texto: 'Serbia' },
  { valor: 'SEYC', texto: 'Seychelles' },
  { valor: 'SLEO', texto: 'Sierra Leona' },
  { valor: 'SING', texto: 'Singapur' },
  { valor: 'SVK', texto: 'Eslovaquia' },
  { valor: 'SVN', texto: 'Eslovenia' },
  { valor: 'SLMN', texto: 'Islas Salomón' },
  { valor: 'SOMA', texto: 'Somalia' },
  { valor: 'SAFR', texto: 'Sudáfrica' },
  { valor: 'SSDN', texto: 'Sudán del Sur' },
  { valor: 'SPN', texto: 'España' },
  { valor: 'SRL', texto: 'Sri Lanka' },
  { valor: 'SHEL', texto: 'Santa Elena' },
  { valor: 'STCN', texto: 'San Cristóbal y Nieves' },
  { valor: 'SLCA', texto: 'Santa Lucía' },
  { valor: 'STVN', texto: 'San Vicente y las Granadinas' },
  { valor: 'XXX', texto: 'Apátrida' },
  { valor: 'SUDA', texto: 'Sudán' },
  { valor: 'SURM', texto: 'Surinam' },
  { valor: 'SWDN', texto: 'Suecia' },
  { valor: 'SWTZ', texto: 'Suiza' },
  { valor: 'SYR', texto: 'Siria' },
  { valor: 'TWAN', texto: 'Taiwán' },
  { valor: 'TJK', texto: 'Tayikistán' },
  { valor: 'TAZN', texto: 'Tanzania' },
  { valor: 'THAI', texto: 'Tailandia' },
  { valor: 'TMOR', texto: 'Timor Oriental' },
  { valor: 'TOGO', texto: 'Togo' },
  { valor: 'TONG', texto: 'Tonga' },
  { valor: 'TRIN', texto: 'Trinidad y Tobago' },
  { valor: 'TNSA', texto: 'Túnez' },
  { valor: 'TRKY', texto: 'Turquía' },
  { valor: 'TKM', texto: 'Turkmenistán' },
  { valor: 'TCIS', texto: 'Islas Turcas y Caicos' },
  { valor: 'TUV', texto: 'Tuvalu' },
  { valor: 'UGAN', texto: 'Uganda' },
  { valor: 'UKR', texto: 'Ucrania' },
  { valor: 'UAE', texto: 'Emiratos Árabes Unidos' },
  { valor: 'GRBR', texto: 'Reino Unido' },
  { valor: 'USA', texto: 'Estados Unidos de América' },
  { valor: 'URU', texto: 'Uruguay' },
  { valor: 'UZB', texto: 'Uzbekistán' },
  { valor: 'VANU', texto: 'Vanuatu' },
  { valor: 'VENZ', texto: 'Venezuela' },
  { valor: 'VTNM', texto: 'Vietnam' },
  { valor: 'BRVI', texto: 'Islas Vírgenes Británicas' },
  { valor: 'WAFT', texto: 'Wallis y Futuna' },
  { valor: 'SSAH', texto: 'Sahara Occidental' },
  { valor: 'YEM', texto: 'Yemen' },
  { valor: 'ZAMB', texto: 'Zambia' },
  { valor: 'ZIMB', texto: 'Zimbabue' },
] as const satisfies readonly OpcionCatalogo[]
