// Archivo generado por scripts/generarCatalogos.mjs — no editar a mano.
// Fuente: docs/catalogo_proposito_viaje_especifico.md

import type { OpcionCatalogo } from './tipos'

// Mapa valor de propositoViaje -> opciones de proposito especifico.
// El DS-160 recarga el select hijo cuando cambia el padre; aca es un lookup.
export const propositoViajeEspecifico: Record<string, OpcionCatalogo[]> = {
  B: [
    { valor: 'B1-B2', texto: 'Negocios o turismo (visitante temporal) (B1/B2)' },
    { valor: 'B1-CF', texto: 'Negocios/conferencia (B1)' },
    { valor: 'B2-TM', texto: 'Turismo/tratamiento médico (B2)' },
  ],
  A: [
    { valor: 'A1-AM', texto: 'Embajador o ministro público (A1)' },
    { valor: 'A1-CH', texto: 'Hijo/hija de un A1 (A1)' },
    { valor: 'A1-DP', texto: 'Diplomático de carrera/funcionario consular (A1)' },
    { valor: 'A1-SP', texto: 'Cónyuge de un A1 (A1)' },
    { valor: 'A2-CH', texto: 'Hijo/hija de un A2 (A2)' },
    { valor: 'A2-EM', texto: 'Funcionario/empleado extranjero (A2)' },
    { valor: 'A2-SP', texto: 'Cónyuge de un A2 (A2)' },
    { valor: 'A3-CH', texto: 'Hijo/hija de un A3 (A3)' },
    { valor: 'A3-EM', texto: 'Empleado personal de un A1 o A2 (A3)' },
    { valor: 'A3-SP', texto: 'Cónyuge de un A3 (A3)' },
  ],
  C: [
    { valor: 'C1-D', texto: 'Tripulante en tránsito (C1/D)' },
    { valor: 'C1-TR', texto: 'Tránsito (C1)' },
    { valor: 'C2-UN', texto: 'Tránsito a la sede de la ONU (C2)' },
    { valor: 'C3-CH', texto: 'Hijo/hija de un C3 (C3)' },
    { valor: 'C3-EM', texto: 'Empleado personal de un C3 (C3)' },
    { valor: 'C3-FR', texto: 'Funcionario extranjero en tránsito (C3)' },
    { valor: 'C3-SP', texto: 'Cónyuge de un C3 (C3)' },
    { valor: 'C4-NO', texto: 'No ciudadano en tránsito, operación de aligeramiento (C4)' },
    { valor: 'C4-D3', texto: 'Tripulante de aligeramiento en tránsito (C4/D3)' },
  ],
  CNMI: [
    { valor: 'CW1-CW1', texto: 'Trabajador temporal de las CNMI (CW1)' },
    { valor: 'CW2-CH', texto: 'Hijo/hija de un CW1 (CW2)' },
    { valor: 'CW2-SP', texto: 'Cónyuge de un CW1 (CW2)' },
    { valor: 'E2C-E2C', texto: 'Inversionista de largo plazo de las CNMI (E2C)' },
  ],
  D: [
    { valor: 'D-D', texto: 'Tripulante (D)' },
    { valor: 'D3-LI', texto: 'Tripulante de aligeramiento (D3)' },
  ],
  E: [
    { valor: 'E1-CH', texto: 'Hijo/hija de un E1 (E1)' },
    { valor: 'E1-EX', texto: 'Ejecutivo/gerente/empleado esencial (E1)' },
    { valor: 'E1-SP', texto: 'Cónyuge de un E1 (E1)' },
    { valor: 'E1-TR', texto: 'Comerciante por tratado (E1)' },
    { valor: 'E2-CH', texto: 'Hijo/hija de un E2 (E2)' },
    { valor: 'E2-EX', texto: 'Ejecutivo/gerente/empleado esencial (E2)' },
    { valor: 'E2-SP', texto: 'Cónyuge de un E2 (E2)' },
    { valor: 'E2-TR', texto: 'Inversionista por tratado (E2)' },
    { valor: 'E3D-CH', texto: 'Hijo/hija de un E3 (E3D)' },
    { valor: 'E3D-SP', texto: 'Cónyuge de un E3 (E3D)' },
  ],
  F: [
    { valor: 'F1-F1', texto: 'Estudiante (F1)' },
    { valor: 'F2-CH', texto: 'Hijo/hija de un F1 (F2)' },
    { valor: 'F2-SP', texto: 'Cónyuge de un F1 (F2)' },
  ],
  G: [
    { valor: 'G1-CH', texto: 'Hijo/hija de un G1 (G1)' },
    { valor: 'G1-G1', texto: 'Representante principal (G1)' },
    { valor: 'G1-SP', texto: 'Cónyuge de un G1 (G1)' },
    { valor: 'G1-ST', texto: 'Personal del representante principal (G1)' },
    { valor: 'G2-CH', texto: 'Hijo/hija de un G2 (G2)' },
    { valor: 'G2-RP', texto: 'Representante (G2)' },
    { valor: 'G2-SP', texto: 'Cónyuge de un G2 (G2)' },
    { valor: 'G3-CH', texto: 'Hijo/hija de un G3 (G3)' },
    { valor: 'G3-RP', texto: 'Representante de país no reconocido/no miembro (G3)' },
    { valor: 'G3-SP', texto: 'Cónyuge de un G3 (G3)' },
    { valor: 'G4-CH', texto: 'Hijo/hija de un G4 (G4)' },
    { valor: 'G4-G4', texto: 'Empleado de organización internacional (G4)' },
    { valor: 'G4-SP', texto: 'Cónyuge de un G4 (G4)' },
    { valor: 'G5-CH', texto: 'Hijo/hija de un G5 (G5)' },
    { valor: 'G5-EM', texto: 'Empleado personal de un G1, 2, 3 o 4 (G5)' },
    { valor: 'G5-SP', texto: 'Cónyuge de un G5 (G5)' },
  ],
  H: [
    { valor: 'H1B-H1B', texto: 'Ocupación especializada (H1B)' },
    { valor: 'H1B1-CHL', texto: 'Ocupación especializada chilena (H1B1)' },
    { valor: 'H1B1-SGP', texto: 'Ocupación especializada singapurense (H1B1)' },
    { valor: 'H1C-NR', texto: 'Enfermero/a en área con escasez de personal (H1C)' },
    { valor: 'H2A-AG', texto: 'Trabajador agrícola (H2A)' },
    { valor: 'H2B-NA', texto: 'Trabajador no agrícola (H2B)' },
    { valor: 'H3-TR', texto: 'Aprendiz/capacitando (H3)' },
    { valor: 'H4-CH', texto: 'Hijo/hija de un H (H4)' },
    { valor: 'H4-SP', texto: 'Cónyuge de un H (H4)' },
  ],
  I: [
    { valor: 'I-CH', texto: 'Hijo/hija de un I (I)' },
    { valor: 'I-FR', texto: 'Representante de medios extranjeros (I)' },
    { valor: 'I-SP', texto: 'Cónyuge de un I (I)' },
  ],
  J: [
    { valor: 'J1-J1', texto: 'Visitante de intercambio (J1)' },
    { valor: 'J2-CH', texto: 'Hijo/hija de un J1 (J2)' },
    { valor: 'J2-SP', texto: 'Cónyuge de un J1 (J2)' },
  ],
  K: [
    { valor: 'K1-K1', texto: 'Prometido(a) de ciudadano estadounidense (K1)' },
    { valor: 'K2-K2', texto: 'Hijo/hija de un K1 (K2)' },
    { valor: 'K3-K3', texto: 'Cónyuge de ciudadano estadounidense (K3)' },
    { valor: 'K4-K4', texto: 'Hijo/hija de un K3 (K4)' },
  ],
  L: [
    { valor: 'L1-L1', texto: 'Transferido dentro de la misma empresa (L1)' },
    { valor: 'L2-CH', texto: 'Hijo/hija de un L1 (L2)' },
    { valor: 'L2-SP', texto: 'Cónyuge de un L1 (L2)' },
  ],
  M: [
    { valor: 'M1-M1', texto: 'Estudiante (M1)' },
    { valor: 'M2-CH', texto: 'Hijo/hija de un M1 (M2)' },
    { valor: 'M2-SP', texto: 'Cónyuge de un M1 (M2)' },
    { valor: 'M3-M3', texto: 'Estudiante fronterizo/conmutante (M3)' },
  ],
  N: [
    { valor: 'N8-CH', texto: 'Hijo/hija de un N8 (N9)' },
    { valor: 'N8-N8', texto: 'Padre/madre de cierto inmigrante especial (N8)' },
  ],
  NATO: [
    { valor: 'NATO1-CH', texto: 'Hijo/hija de NATO1 (NATO1)' },
    { valor: 'NATO1-PR', texto: 'Representante principal (NATO1)' },
    { valor: 'NATO1-SP', texto: 'Cónyuge de NATO1 (NATO1)' },
    { valor: 'NATO2-CH', texto: 'Hijo/hija de NATO2 (NATO2)' },
    { valor: 'NATO2-RP', texto: 'Representante (NATO2)' },
    { valor: 'NATO2-SP', texto: 'Cónyuge de NATO2 (NATO2)' },
    { valor: 'NATO3-CH', texto: 'Hijo/hija de NATO3 (NATO3)' },
    { valor: 'NATO3-SP', texto: 'Cónyuge de NATO3 (NATO3)' },
    { valor: 'NATO3-ST', texto: 'Personal administrativo/de oficina (NATO3)' },
    { valor: 'NATO4-CH', texto: 'Hijo/hija de NATO4 (NATO4)' },
    { valor: 'NATO4-OF', texto: 'Funcionario (NATO4)' },
    { valor: 'NATO4-SP', texto: 'Cónyuge de NATO4 (NATO4)' },
    { valor: 'NATO5-CH', texto: 'Hijo/hija de NATO5 (NATO5)' },
    { valor: 'NATO5-EX', texto: 'Experto (NATO5)' },
    { valor: 'NATO5-SP', texto: 'Cónyuge de NATO5 (NATO5)' },
    { valor: 'NATO6-CH', texto: 'Hijo/hija de NATO6 (NATO6)' },
    { valor: 'NATO6-SP', texto: 'Cónyuge de NATO6 (NATO6)' },
    { valor: 'NATO6-ST', texto: 'Personal civil (NATO6)' },
    { valor: 'NATO7-CH', texto: 'Hijo/hija de NATO7 (NATO7)' },
    { valor: 'NATO7-EM', texto: 'Empleado personal de NATO1 a NATO6 (NATO7)' },
    { valor: 'NATO7-SP', texto: 'Cónyuge de NATO7 (NATO7)' },
  ],
  O: [
    { valor: 'O1-EX', texto: 'Habilidad extraordinaria (O1)' },
    { valor: 'O2-AL', texto: 'Extranjero que acompaña/asiste (O2)' },
    { valor: 'O3-CH', texto: 'Hijo/hija de un O1 u O2 (O3)' },
    { valor: 'O3-SP', texto: 'Cónyuge de un O1 u O2 (O3)' },
  ],
  P: [
    { valor: 'P1-P1', texto: 'Extranjero internacionalmente reconocido (P1)' },
    { valor: 'P2-P2', texto: 'Artista/animador de programa de intercambio (P2)' },
    { valor: 'P3-P3', texto: 'Artista/animador de programa cultural (P3)' },
    { valor: 'P4-CH', texto: 'Hijo/hija de un P1, P2 o P3 (P4)' },
    { valor: 'P4-SP', texto: 'Cónyuge de un P1, P2 o P3 (P4)' },
  ],
  Q: [{ valor: 'Q1-Q1', texto: 'Visitante de intercambio cultural (Q1)' }],
  R: [
    { valor: 'R1-R1', texto: 'Trabajador religioso (R1)' },
    { valor: 'R2-CH', texto: 'Hijo/hija de un R1 (R2)' },
    { valor: 'R2-SP', texto: 'Cónyuge de un R1 (R2)' },
  ],
  S: [{ valor: 'S7-S7', texto: 'Familiar de un informante (S7)' }],
  T: [
    { valor: 'T1-T1', texto: 'Víctima de trata de personas (T1)' },
    { valor: 'T2-SP', texto: 'Cónyuge de un T1 (T2)' },
    { valor: 'T3-CH', texto: 'Hijo/hija de un T1 (T3)' },
    { valor: 'T4-PR', texto: 'Padre/madre de un T1 (T4)' },
    { valor: 'T5-SB', texto: 'Hermano/hermana de un T1 (T5)' },
    { valor: 'T6-CB', texto: 'Hijo/hija adulto o menor de un beneficiario derivado de un T1 (T6)' },
  ],
  'TD/TN': [
    { valor: 'TD-CH', texto: 'Hijo/hija de un TN (TD)' },
    { valor: 'TD-SP', texto: 'Cónyuge de un TN (TD)' },
  ],
  U: [
    { valor: 'U1-U1', texto: 'Víctima de un delito (U1)' },
    { valor: 'U2-SP', texto: 'Cónyuge de un U1 (U2)' },
    { valor: 'U3-CH', texto: 'Hijo/hija de un U1 (U3)' },
    { valor: 'U4-PR', texto: 'Padre/madre de un U1 (U4)' },
    { valor: 'U5-SB', texto: 'Hermano/hermana de un U1 (U5)' },
  ],
  'PAROLE-BEN': [
    { valor: 'PRL-PARCIS', texto: 'PARCIS (libertad condicional aprobada por USCIS)' },
  ],
}
